### ISSUE TITLE
Method not found exceptions after adding Datadog.Trace nuget package

### ISSUE THREAD

**Issue by dziedrius** [DataDog/dd-trace-dotnet#1274]
We've been using Datadog APM in .net 3.1 app for couple months now and decided to add custom scopes in some parts of the app. 
After adding Datadog.Trace version 1.24.0 nuget package I see following in the logs:

```
System.MissingMethodException: Method not found: 'Datadog.Trace.Scope Datadog.Trace.Tracer.StartActiveWithTags(System.String, Datadog.Trace.ISpanContext, System.String, System.Nullable`1<System.DateTimeOffset>, Boolean, Boolean, Datadog.Trace.Tagging.ITags)'.
at Datadog.Trace.ClrProfiler.ScopeFactory.CreateDbCommandScope(Tracer tracer, IDbCommand command)
at Datadog.Trace.ClrProfiler.Integrations.AdoNet.NpgsqlCommandIntegration.ExecuteReader(Object command, Int32 opCode, Int32 mdToken, Int64 moduleVersionPtr)
at Npgsql.PostgresDatabaseInfo.LoadBackendTypes(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
at Npgsql.PostgresDatabaseInfo.LoadPostgresInfo(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
at Npgsql.PostgresDatabaseInfoFactory.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
at Npgsql.NpgsqlDatabaseInfo.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
at Npgsql.NpgsqlConnector.LoadDatabaseInfo(NpgsqlTimeout timeout, Boolean async)
at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlConnection.Open()
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
```
I've checked decompiled version, there's following method:
```
internal Scope StartActiveWithTags(string operationName, ISpanContext parent = null, string serviceName = null, DateTimeOffset? startTime = null, bool ignoreActiveScope = false, bool finishOnClose = true, ITags tags = null, ulong? spanId = null)
```
it has additional nullable parameter spanId.

**Comment by andrewlock** [comment]
Hi, issues like these typically arise when your NuGet version of the Tracer is out-of-sync with the MSI installed version of the tracer used for automatic instrumentation. Could you please check which version of the MSI tracer (or equivalent on Linux) that you're using? Thanks

**Comment by dziedrius** [comment]
Yep, you're right, datadog-dotnet-apm-${TRACER_VERSION}-musl.tar.gz version was out of sync with nuget version.
I think this issue may be closed.
