### ISSUE TITLE
Azure Extensions 1.6.0 and tracer 1.28.7 throws error at startup when settings environment variable

### ISSUE THREAD

**Issue by Havunen** [DataDog/dd-trace-dotnet#1790]
We have .net5 web application and we are trying to set up Datadog version to envrionment variables at application startup.
But its throwing exception

Code in startup:
```
// Add datadog version to environment variables
Environment.SetEnvironmentVariable("DD_VERSION", this.Configuration["DD_Version"], EnvironmentVariableTarget.Machine);
```

Application fails to startup:

![image](https://user-images.githubusercontent.com/2021355/133763952-07a5db5b-90eb-4f0c-bb59-dae1197e1603.png)

In application event log there is error:

```
Application '/LM/W3SVC/1992865732/ROOT/name' with physical root 'D:\home\site\wwwroot\name\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
2021-09-17 09:48:07 GMT | DSD | ERROR | (pkg/metadata/gohai/gohai.go:63 in getGohaiInfo) | Failed to retrieve network metadata: fork/exec D:\Windows\system32\ipconfig.exe: Access is denied.
2021-09-17 09:48:07 GMT | DSD | WARN | (pkg/metadata/helper.go:94 in SetupMetadataCollection) | Metadata collection disabled, only do that if another agent/dogstatsd is running on this host
Unhandled exception. System.Security.SecurityException: Requested registry access is not allowed.
   at Internal.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at System.Environment.OpenEnvironmentKeyIfExists(Boolean fromMachine, Boolean writable)
   at System.Environment.SetEnvironmentVariableFromRegistry(String variable, String value, Boolean fromMachine)
   at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
   at Visma.Severa.Rest.Api.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\git\Severa-Backend\Visma.Severa.Rest.API\Startup.cs:line 260
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Visma.Severa.Rest.Api.Program.Main(String[] args) in C:\git\Severa-Backend\Visma.Severa.Rest.API\Program.cs:line 14

Process Id: 13064.
File Version: 15.0.21196.9. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: c663adee8e64ba5d379fa0edfb8201984a7df7d0
```

Also opened ticket here: https://github.com/DataDog/gohai/issues/81

**Comment by andrewlock** [comment]
Hi @Havunen, there are a few issues here:

* Version 1.6.0 of the AAS extension is only compatible with version 1.28.6 of the .NET Tracer, as mentioned [in the release notes](https://github.com/DataDog/datadog-aas-extension/releases/tag/v1.6.0).
* You shouldn't set environment variables required by the tracer from _within_ the application, you need to set them within AAS itself
* The error you're seeing looks unrelated to the tracer, and instead is because you're trying to set the environment variable from within the AAS application

Hope that helps!

**Comment by Havunen** [comment]
> You shouldn't set environment variables required by the tracer from within the application, you need to set them within AAS itself

Okay. Do you have some examples how it could be done smoothly, there is one issue at least that setting azure app service variable will reboot the service. 

Is there some guide how we could easily keep datadog version variable updated with continous deployment, if it cannot be set from the application itself?

**Comment by andrewlock** [comment]
> there is one issue at least that setting azure app service variable will reboot the service.

Presumably you essentially need to restart the service _anyway_ if you're deploying a new version (when you update the `DD_VERSION` value?)

> Is there some guide how we could easily keep datadog version variable updated with continous deployment, if it cannot be set from the application itself?

If you can't set environment variables (the preferred approach) [could you use a datadog.json file as described in the docs](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core/?tab=jsonfile#configuration)?
