### ISSUE TITLE
HttpHeadersCodec.Extract Throws ArgumentException because a default trace-id isn't found

### ISSUE THREAD

**Issue by reenrik** [DataDog/dd-trace-dotnet#209]
**Describe the bug**
I'm using _Datadog.Trace.OpenTracing_ with [_OpenTracing_](https://github.com/opentracing/opentracing-csharp) and _[OpenTracing.Contrib.NetCore](https://github.com/opentracing-contrib/csharp-netcore)_ to attempt some automatic tracing. 

When an my MVC app is the "top" of the execution chain, the DD tracer seems to attempt and then fails to extract two headers: _x-datadog-parent-id_ and _x-datadog-trace-id_ and throws an _ArgumentException_. 

[https://github.com/DataDog/dd-trace-csharp/blob/8d49793b905dff599671858aa76c99cd3726e417/src/Datadog.Trace.OpenTracing/HttpHeadersCodec.cs](https://github.com/DataDog/dd-trace-csharp/blob/8d49793b905dff599671858aa76c99cd3726e417/src/Datadog.Trace.OpenTracing/HttpHeadersCodec.cs)

**To Reproduce**
- Use OpenTracing.Contrib to inject a Tracer into an MVC web api
- Manually instrument a method

**Expected behavior**
If header extraction fails, then assume this is the root application and set default _x-datadog-trace-id_ and allow for an empty _x-datadog-parent-id_ 

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual with NuGet package
- Tracer version: 0.5.0
- OS: Windows 10
- CLR: .NET Core 2.1

**Stack trace**

```
System.ArgumentException: x-datadog-parent-id should be set.
   at Datadog.Trace.OpenTracing.HttpHeadersCodec.Extract(Object carrier)
   at Datadog.Trace.OpenTracing.OpenTracingTracer.Extract[TCarrier](IFormat`1 format, TCarrier carrier)
   at OpenTracing.Contrib.NetCore.AspNetCore.HostingEventProcessor.ProcessEvent(String eventName, Object arg) in C:\projects\csharp-netcore\src\OpenTracing.Contrib.NetCore\AspNetCore\HostingEventProcessor.cs:line 50
   at OpenTracing.Contrib.NetCore.AspNetCore.AspNetCoreDiagnostics.OnNext(String eventName, Object untypedArg) in C:\projects\csharp-netcore\src\OpenTracing.Contrib.NetCore\AspNetCore\AspNetCoreDiagnostics.cs:line 51
   at OpenTracing.Contrib.NetCore.Internal.DiagnosticListenerObserver.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value) in C:\projects\csharp-netcore\src\OpenTracing.Contrib.NetCore\Internal\DiagnosticListenerObserver.cs:line 46
```

**Comment by lucaspimentel** [comment]
Hey, @reenrik. We are going to look into this issue soon as we add distributed tracing support to the .NET Tracer. Just wanted to give you a heads up.

**Comment by macrogreg** [comment]
Hi @reenrik ,

Just re-discovered this submission. It is embarrassingly old and stale. A lot has changed since then, I am guessing this is no longer current. I will close this for now, but please feel free to re-open if I guessed wrong.

Again - my sorry for loosing track of this! :)
