### ISSUE TITLE
100% error rate when response content is null

### ISSUE THREAD

**Issue by odyth** [DataDog/dd-trace-dotnet#260]
One of my API calls gets 100% error rate in datadog and the stack trace when you look at the trace in datadog is below. The only thing that is different about this call is the content would be null (it's a mock endpoint for the moment). The method returns a HttpResponseMessage and the content would be null with a status code of 204 no content.

```
at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at Datadog.Trace.ClrProfiler.Integrations.AspNetWebApi2Integration.<ExecuteAsyncInternal>d__2.MoveNext()
```

**Comment by colin-higgins** [comment]
Hey Odyth, thanks for the feedback. We are going to be looking into this soon. Thanks for reporting it.

**Comment by odyth** [comment]
I think this might have been resolved in one of your previous releases. I haven't seen this issue, sorry for not closing this sooner.
