### ISSUE TITLE
Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)

### ISSUE THREAD

**Issue by s-tokutake** [DataDog/dd-trace-dotnet#475]
**Describe the bug**

- System.IO.FileLoadException occurred . The detail error message is below.

```

Exception: System.SystemException

Message: Failed to create AppDomain.

StackTrace:    at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironmentAndReportErrors(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)
   at System.Web.Hosting.ApplicationManager.GetAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)
   at System.Web.Hosting.ApplicationManager.CreateObjectInternal(String appId, Type type, IApplicationHost appHost, Boolean failIfExists, HostingEnvironmentParameters hostingParameters)
   at System.Web.Hosting.ProcessHost.StartApplication(String appId, String appPath, Object& runtimeInterface)

InnerException: System.IO.FileLoadException

Message: Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)

StackTrace:    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateAppDomainManager()
   at System.AppDomain.Setup(Object arg)
   at System.AppDomain.nCreateDomain(String friendlyName, AppDomainSetup setup, Evidence providedSecurityInfo, Evidence creatorsSecurityInfo, IntPtr parentSecurityDescriptor)
   at System.AppDomain.InternalCreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
   at System.AppDomain.CreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)

```

**To Reproduce**

1. install ` datadog-dotnet-apm-1.6.1-x64.msi `
2. exec ` iisreset `
3. access the application.

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic with msi installer
- 1.6.1
- OS: Windows Server 2016 R2
- CLR: NET Framework 4.7.2 /  ASP.NET WebForms Application

**Additional context**

- I run 4 asp.net application in a website. 3 apps are nested.  And only one app is failed to start by this error. 

```
─ App1 (asp.net webforms) ok
        ├─App2(asp.net mvc) ok
        ├─App3(asp.net webapi) ok
        └─App4(asp.net webforms) System.IO.FileLoadException occurred!!
```

- What kind of situations is this exception happen?

**Comment by colin-higgins** [comment]
Hi @s-tokutake, is this new to 1.6.1 or did this happen in 1.6.0 as well?
Is there anything about the nested web forms `App4` that is particularly different from the others? 
Does it have specific security settings?

**Comment by s-tokutake** [comment]
@colin-higgins thanks for your reply.

>  is this new to 1.6.1 or did this happen in 1.6.0 as well?

- This also happens in 1.6.0.

> Does it have specific security settings?

- No. It is a normal web app. It provides SOAP APIs. but I think this is not special.

**Comment by colin-higgins** [comment]
@s-tokutake Do you know if any of the web applications are consuming the Nuget package (https://www.nuget.org/packages/Datadog.Trace.ClrProfiler.Managed/)?
If they are, would you mind listing the versions for each app?
In fact, if you wouldn't mind sharing the dependencies & versions for each application, that could greatly help us troubleshoot this issue. Thank you.

**Comment by s-tokutake** [comment]
> Do you know if any of the web applications are consuming the Nuget package )?

No. These apps don't use ` Datadog.Trace.ClrProfiler.Managed ` .

**Comment by 0c370t** [comment]
Would like to chime in and note that we are also having this issue, our application has 1.6.1, and does use the `Datadog.Trace.ClrProfiler.Managed`

Are there any fixes for this yet?

**Comment by prahutomo** [comment]
I had the same issue. The workaround is to create 
a new registry DWORD value called LoaderOptimization under “HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework” and set the value 1. Then do issreset.

**Comment by lucaspimentel** [comment]
Thanks, @prahutomo. [Here is some documentation](https://docs.microsoft.com/en-us/dotnet/api/system.loaderoptimization?view=netframework-4.8) on the valid values for that setting.

Please keep in mind that forcing the loader optimization value to 1 (`SingleDomain`) is a _workaround_. The drawback is that multiple AppDomains in the same process will no longer be able share resources. For users with many applications running in the same IIS AppPool, this setting can increase memory usage considerably. Please use with caution!

Btw, we are actively working (https://github.com/DataDog/dd-trace-dotnet/pull/505) on loading our tracer assemblies in a different way that doesn't interfere with the ability to share assemblies between AppDomains. This should eliminate the error without the need for this workaround.

**Comment by colin-higgins** [comment]
While we are working through this. If anybody with the issue is able and willing to enable fuslogvw so that we can have a full picture of the issue you are having, that would be very helpful.
Zipping up the directory and sending it to us would be greatly appreciated.
![image](https://user-images.githubusercontent.com/1801443/64968075-8ff9e800-d86f-11e9-957a-5c6c100a81c9.png)

**Comment by lucaspimentel** [comment]
We've done several changes over the last few months to alleviate this issue, if not solve it completely. There is also the workaround of changing the `LoaderOptimization` setting mentioned above.

We are closing this issue. Please re-open or create a new github issue if you encounter this again. Thanks.

**Comment by rdvanbuuren-gasunie** [comment]
This also fixed our problem creating assembly redirects. So it looks like it issue is still present nowadays.

**Comment by TomSkidmore** [comment]
Can confirm in mid 2025 this is still an issue and the workaround above gets thing back up and running. Like the commenter above, mine was just local IIS through Visual Studio. Adding in the DWORD sorted it, no iisreset required

**Comment by zacharycmontoya** [comment]
Hi Tom, I'm surprised to still see this be an issue so I'd like to learn more about your application. Can you share share the NuGet package dependencies you have any any assembly redirects authored for your application?

**Comment by Hugo-Dahl-Tyler** [comment]
Just ran into this today as well. VS2022 Pro (v17.14.13 Preview 1.0)
Multi-project solution, whether running `Update-Packages -Project Project.Name` or `Add-BindingRedirect -Project Project.Name`.

One possible additional context piece which _may_(?) be a factor is that there are multiple sources in the `NuGet.config` file in the repository's root.

**Comment by drfish** [comment]
I just had to apply the workaround in 17.14.31. I also have a multi-project solution with multiple nuget sources like the last person. Other people in the organization load without issues, heck yesterday I too didn't have any problems, then I closed and reopened vs and it showed up.
