### ISSUE TITLE
Tracer agent stops reporting APM data

### ISSUE THREAD

**Issue by odyth** [DataDog/dd-trace-dotnet#5179]
Running 2.46.0 on windows server 2022 with .net core 6 web app hosted in iis. APM will work fine until new code is deployed or the app pool is recycled (happens nightly). Once in this state APM won't work again until you reboot the server. Noticed this exception in the logs possibly related (came from dotnet-tracer-loader-w3wp-4360.log)?

```
[2024-02-11 10:00:03.120 +00:00] Error when invoking managed method: Datadog.Trace.ClrProfiler.Instrumentation.Initialize
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Datadog.Trace.Configuration.GlobalConfigurationSource' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Datadog.Trace.Configuration.GlobalConfigurationSource.CreateDefaultConfigurationSource()
   at Datadog.Trace.Configuration.GlobalConfigurationSource..cctor() in c:\mnt\tracer\src\Datadog.Trace\Configuration\ConfigurationSources\GlobalConfigurationSource.cs:line 24
   --- End of inner exception stack trace ---
   at Datadog.Trace.Configuration.GlobalConfigurationSource.get_Instance() in c:\mnt\tracer\src\Datadog.Trace\Configuration\ConfigurationSources\GlobalConfigurationSource.cs:line 24
   at Datadog.Trace.Configuration.TracerSettings.FromDefaultSourcesInternal() in c:\mnt\tracer\src\Datadog.Trace\Configuration\TracerSettings.cs:line 961
   at Datadog.Trace.TracerManagerFactory.CreateTracerManager(ImmutableTracerSettings settings, IAgentWriter agentWriter, ITraceSampler sampler, IScopeManager scopeManager, IDogStatsd statsd, RuntimeMetricsWriter runtimeMetrics, DirectLogSubmissionManager logSubmissionManager, ITelemetryController telemetry, IDiscoveryService discoveryService, DataStreamsManager dataStreamsManager, IRemoteConfigurationManager remoteConfigurationManager, IDynamicConfigurationManager dynamicConfigurationManager, ITracerFlareManager tracerFlareManager) in c:\mnt\tracer\src\Datadog.Trace\TracerManagerFactory.cs:line 105
   at Datadog.Trace.TracerManagerFactory.CreateTracerManager(ImmutableTracerSettings settings, TracerManager previous) in c:\mnt\tracer\src\Datadog.Trace\TracerManagerFactory.cs:line 53
   at Datadog.Trace.TracerManager.CreateInitializedTracer(ImmutableTracerSettings settings, TracerManagerFactory factory) in c:\mnt\tracer\src\Datadog.Trace\TracerManager.cs:line 600
   at Datadog.Trace.TracerManager.<>c.<get_Instance>b__9_0() in c:\mnt\tracer\src\Datadog.Trace\TracerManager.cs:line 117
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Datadog.Trace.TracerManager.get_Instance() in c:\mnt\tracer\src\Datadog.Trace\TracerManager.cs:line 113
   at Datadog.Trace.Tracer..ctor(TracerManager tracerManager) in c:\mnt\tracer\src\Datadog.Trace\Tracer.cs:line 109
   at Datadog.Trace.Tracer.get_Instance() in c:\mnt\tracer\src\Datadog.Trace\Tracer.cs:line 147
   at Datadog.Trace.ClrProfiler.Instrumentation.InitializeNoNativeParts(Stopwatch sw) in c:\mnt\tracer\src\Datadog.Trace\ClrProfiler\Instrumentation.cs:line 347
   at Datadog.Trace.ClrProfiler.Instrumentation.Initialize() in c:\mnt\tracer\src\Datadog.Trace\ClrProfiler\Instrumentation.cs:line 103
   at Datadog.Trace.ClrProfiler.InstrumentationLoader..ctor() in c:\mnt\tracer\src\Datadog.Trace\ClrProfiler\InstrumentationLoader.cs:line 24
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Datadog.Trace.ClrProfiler.Managed.Loader.Startup.TryInvokeManagedMethod(String typeName, String methodName, String loaderHelperTypeName) in c:\mnt\tracer\src\Datadog.Trace.ClrProfiler.Managed.Loader\Startup.cs:line 95
```

**Comment by andrewlock** [comment]
Hi @odyth - I have a question about the app pool you're using: is it set to "[No managed Code](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-8.0#create-the-iis-site)", e.g.:

![image](https://github.com/DataDog/dd-trace-dotnet/assets/18755388/bdbaccce-7508-409f-91c5-6cfc9fa88e74)

It looks like the .NET Framework dll has been loaded (which is why it's trying to load `System.Configuration.ConfigurationManager`), and using a .NET Framework CLR version inside the app pool might be causing that.

Thanks!

**Comment by odyth** [comment]
that fixed it. thanks
