### ISSUE TITLE
InvalidProgramException after successful MySQL connection

### ISSUE THREAD

**Issue by ksjoberg** [DataDog/dd-trace-dotnet#541]
**Describe the bug**
After a successful MySQL connection is initiated, the program crashes with an InvalidProgramException inside `MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)` if the DataDog Tracer MSI is installed on the host machine.

**To Reproduce**
I have provided a repro here: https://github.com/ksjoberg/dd-trace-repro1
I set this up in IIS, but I believe also regular/console applications are affected.

**Expected behavior**
The tracer/agent should instrument the assemblies transparently.

**Runtime environment:**
- Instrumentation mode: automatic with msi installer
- Tracer version: 1.8.0
- OS: Windows 10 build 1903
- CLR: .NET Framework 4.8

**Additional context**
This is obviously major issue for us.

**Comment by lucaspimentel** [comment]
Thanks for reporting this, @ksjoberg. I looked at the repro repo (heh) and there doesn't seem to be any code there, only a `web.config` and the MySQL assemblies. Am I missing something, or this is enough to throw the exception?

**Comment by zacharycmontoya** [comment]
Thanks for the report! @lucaspimentel I can start investigating this issue today

**Comment by zacharycmontoya** [comment]
Sorry, it looks like closing the PR automatically closed this issue. The fix has been merged and will be included in our next release which we hope to get out promptly. Thanks again @ksjoberg for the repro, that made the issue much easier to diagnose and fix.

**Comment by ksjoberg** [comment]
You guys think this issue relates to #359 ? It seemed to crash somewhere in the same general location. Any idea when this bug was introduced?

**Comment by bobuva** [comment]
Hey @ksjoberg, do you still have the dump files that you mentioned earlier? I would like to take a look at them before saying whether or not the fix will address it?

**Comment by bobuva** [comment]
This has been fixed in [1.9.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/1.9.0)

**Comment by fjmorel** [comment]
I got an InvalidProgramException again this morning on 1.9.0. It's an .Net Core 2.2 app running in Docker with the k8s agent.

```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Rethrow(Object )
   at Datadog.Trace.ClrProfiler.Integrations.AspNetCoreMvc2Integration.Rethrow(Object context, Int32 opCode, Int32 mdToken, Int64 moduleVersionPtr)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Elmah.Io.AspNetCore.ElmahIoMiddleware.Invoke(HttpContext context)
```

**Comment by colin-higgins** [comment]
Hi @fjmorel 
Would you mind opening a new issue so that we can track this?
Helpful information would include:
 - the operating system and version
 - the precise runtime version
 - the version of mvc
 - the version of elmah
