### ISSUE TITLE
InvalidProgramException in 1.9.0 on .NET Core 2.2

### ISSUE THREAD

**Issue by fjmorel** [DataDog/dd-trace-dotnet#568]
**Describe the bug**
API throws an exception rather than completing request

**To Reproduce**
1. Do lots of API requests, and eventually there will be a period of time where many of them throw this exception

**Expected behavior**
Exception is not thrown, and API requests completes normally.

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual with NuGet package
- Tracer version: 1.9.0
- OS: docker image `microsoft/dotnet:2.2-aspnetcore-runtime` in EKS kubernetes cluster
- CLR: .Net Core 2.2

**Additional context**
Stack trace:
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Rethrow(Object )
   at Datadog.Trace.ClrProfiler.Integrations.AspNetCoreMvc2Integration.Rethrow(Object context, Int32 opCode, Int32 mdToken, Int64 moduleVersionPtr)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Elmah.Io.AspNetCore.ElmahIoMiddleware.Invoke(HttpContext context)
```

Packages related to Elmah:
```
  <ItemGroup>
    <PackageReference Include="Elmah.Io.AspNetCore" Version="3.7.82" />
    <PackageReference Include="Elmah.Io.Client" Version="3.6.73" />
  </ItemGroup>
```

Mentioned this in #541 after I upgraded to 1.9.0 hoping this issue was fixed. We currently have DataDog tracing disabled in our production API until the issue no longer happens in QA. Maybe related to #564

**Comment by andrewsouthard1** [comment]
Hey all - just wanted to note that our team is investigating this issue and will update once we have a resolution.

**Comment by fjmorel** [comment]
I haven't had this issue since forcing the docker image to use 2.2.8 instead of whatever 2.2 version it had cached. I tried that after seeing comments in #564.

**Comment by lucaspimentel** [comment]
@fjmorel: Thanks for the update. We will close this issue as resolved.

**Comment by fjmorel** [comment]
Sorry, this actually happened again today.

**Comment by lpodolak** [comment]
@fjmorel @lucaspimentel - we also had these InvalidProgramExceptions still occurring on 2.2.8 clr. I updated https://github.com/DataDog/dd-trace-dotnet/issues/564 issue with latest status.

Right now I am working to upgrade our asp.net core apps to latest .net core 3.1, but so far I can't see any datadog traces from none of the automatic integrations we use:
* asp.net core
* httpclient
* postgres
* redis

**Comment by zacharycmontoya** [comment]
@fjmorel @lpodolak do you still see this happening with the latest tracer? In v1.12.0 we updated the way we instrument ASP.NET Core apps, so our integration should no longer affect middleware and this crash should no longer occur.

**Comment by fjmorel** [comment]
I'm out of office this week, but looking forward to trying the upgrade when I get back.

**Comment by lpodolak** [comment]
Thanks, I'll upgrade in next few weeks and I will report back if I see any further occurrence.

**Comment by fjmorel** [comment]
Happened again with 1.13.0 https://app.datadoghq.com/apm/trace/4266900157108038183?env=prod&sort=time&colorBy=service&graphType=flamegraph&shouldShowLegend=true
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DeleteByQueryAsync[TResponse](String index, String type, PostData body, DeleteByQueryRequestParameters requestParameters, CancellationToken ctx)
   at Nest.LowLevelDispatch.DeleteByQueryDispatchAsync[TResponse](IRequest`1 p, SerializableData`1 body, CancellationToken ct)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.DispatchAsync[TRequest,TQueryString,TResponse,TResponseInterface](TRequest request, CancellationToken cancellationToken, Func`3 responseGenerator, Func`4 dispatch)
   at ElasticEntities.ElasticHelpers.DeleteFromIndex[T](IElasticClient client, String guid) in /src/ElasticEntities/ElasticHelpers.cs:line 121
   at NSB_Elastic.Track_Handler.Handle(Elastic_Track msg, IMessageHandlerContext context) in /src/NSB_Elastic/Track_Handler.cs:line 52
```

NEST version is 6.8.3.

This is not an ASP.NET Core app. it's just a .Net Core 3.0 service running in Docker.

**Comment by andrewsouthard1** [comment]
@fjmorel @lpodolak Wanted to confirm with you all - did updating to the latest tracing client resolve your issue? In 1.16.0 we've made a number of improvements to memory overhead as well where it's worth upgrading regardless.

**Comment by lpodolak** [comment]
Hi @andrewsouthard1 
Thanks for the feedback and providing further improvements! No, I did not have time for that and probably I won't probably have it in near future.

**Comment by fjmorel** [comment]
@andrewsouthard1 We've been running 1.13.0 since February 20 without issue in QA. Still have not enabled it in production.

I am keeping track of new releases so I'm hoping to upgrade again this month.

**Comment by andrewsouthard1** [comment]
Hey all - we expect this issue to be resolved in later versions of the tracer.  We're going to close this issue but please do reach out again if you run into any problems!
