### ISSUE TITLE
Automatic instrumentation not working in docker container

### ISSUE THREAD

**Issue by okezieokpara** [DataDog/dd-trace-dotnet#755]
**Describe the bug**
dd-trace-dotnet was successfully installed but not traces have been sent and no logs in /var/log/datadog/dotnet folder

I was able to install the datadog agent and trace-agent on k8s using this article: https://docs.datadoghq.com/agent/kubernetes/?tab=helm
I also enabled apm and logs.
I have installed the tracer in the cotainers using the commands:
```
WORKDIR /tmp
# Setup datadog
RUN curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v1.17.0/datadog-dotnet-apm_1.17.0_amd64.deb
RUN dpkg -i ./datadog-dotnet-apm_1.17.0_amd64.deb
```
And set the required `env` variables in the deployment.yml file:
```
 env:
            - name: CORECLR_ENABLE_PROFILING
              value: "1"
            - name: CORECLR_PROFILER_PATH
              value: "/opt/datadog/Datadog.Trace.ClrProfiler.Native.so"
            - name: DD_INTEGRATIONS
              value: "/opt/datadog/integrations.json"
            - name: DD_DOTNET_TRACER_HOME
              value: "/opt/datadog"
            - name: DD_SERVICE_NAME
              value: "$(projectName)"
            - name: DD_ENV
              value: "$(k8s_namespace)"
            - name: CORECLR_PROFILER
              value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}" 
            - name:  DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"  
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```
The installation seem to be successful because I can see files in the `/opt/datdog/` folder.
```
root@pod-name:/app# ls /opt/datadog
Datadog.Trace.ClrProfiler.Native.so  createLogPath.sh  integrations.json  netstandard2.0
```
But I can' see any logs/trace data on the dashboard yet and nothing logged in `/var/log/datadog/dotnet` folder.

**Tracer version:** datadog-dotnet-apm_1.17.0

PS
This same procedure had worked earlier.
But then the trace-agent wasn't up and running so I got messages like the following in the `/var/log/datadog/dotnet/dotnet-tracer-dotnet-20200610.log`:
```2020-06-10 14:39:40.343 +00:00 [ERR] Unable to communicate with the trace agent at "http://172.31.27.28:8126/v0.4/traces"
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
{ MachineName: ".", Process: "[1 dotnet]", AppDomain: "[1 Kuda.CBA.SystemSetup.API]", TracerVersion: "1.17.0.0" }
2020-06-10 14:39:40.445 +00:00 [ERR] Unable to communicate with the trace agent at "http://172.31.27.28:8126/v0.4/traces"
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
{ MachineName: ".", Process: "[1 dotnet]", AppDomain: "[1 Kuda.CBA.SystemSetup.API]", TracerVersion: "1.17.0.0" }
2020-06-10 14:39:40.647 +00:00 [ERR] Unable to communicate with the trace agent at "http://172.31.27.28:8126/v0.4/traces"
System.Net.Sockets.SocketException (111): Connection refused
```

**Comment by rlaveycal** [comment]
I was about to raise an issue about this. Auto instrumentation of .net core apps running on Linux (or in a container at any rate) seems to have stopped working. Whether this is related to core 3.1 I don't know. We have a 2.2 app working fine.

I have a simple console app (core 3.1) that does this
```c#
                    using var scope = Tracer.Instance.StartActive("run_command");

                    using var conn = new SqlConnection(host);
                    conn.Open();

                    using var command = new SqlCommand("select @@version", conn)
                    {
                        CommandType = CommandType.Text
                    };
                    var r = command.ExecuteNonQuery();
```

When run on Windows 10 the profiler log shows
```
[dotnet.exe] 5784: [info] Datadog CLR Profiler 1.17.0 32-bit
[dotnet.exe] 5784: [info] Environment variables:
[dotnet.exe] 5784: [info]   DD_TRACE_ENABLED=
[dotnet.exe] 5784: [info]   DD_TRACE_DEBUG=false
[dotnet.exe] 5784: [info]   DD_DOTNET_TRACER_HOME=C:\Program Files\Datadog\.NET Tracer\
[dotnet.exe] 5784: [info]   DD_INTEGRATIONS=C:\Program Files\Datadog\.NET Tracer\integrations.json
[dotnet.exe] 5784: [info]   DD_PROFILER_PROCESSES=
[dotnet.exe] 5784: [info]   DD_PROFILER_EXCLUDE_PROCESSES=
[dotnet.exe] 5784: [info]   DD_AGENT_HOST=
[dotnet.exe] 5784: [info]   DD_TRACE_AGENT_PORT=
[dotnet.exe] 5784: [info]   DD_ENV=
[dotnet.exe] 5784: [info]   DD_SERVICE=
[dotnet.exe] 5784: [info]   DD_VERSION=
[dotnet.exe] 5784: [info]   DD_DISABLED_INTEGRATIONS=
[dotnet.exe] 5784: [info]   DD_CLR_DISABLE_OPTIMIZATIONS=
[dotnet.exe] 5784: [info]   DD_TRACE_DOMAIN_NEUTRAL_INSTRUMENTATION=
[dotnet.exe] 5784: [info]   DD_AZURE_APP_SERVICES=
[dotnet.exe] 5784: [info]   APP_POOL_ID=
[dotnet.exe] 5784: [info]   DOTNET_CLI_TELEMETRY_PROFILE=
[dotnet.exe] 5784: [info] Profiler attached.
[dotnet.exe] 5784: [info] JITCompilationStarted: Startup hook registered in function_id=140722345529064 token=100663297 name=SqlConnectionTestCore.Program.Main(), assembly_name=SqlConnectionTestCore app_domain_id=1965957012128 domain_neutral=0
[dotnet.exe] 5784: [info] ModuleLoadFinished: Datadog.Trace.ClrProfiler.Managed.Loader loaded into AppDomain 1965957012128 clrhost
[dotnet.exe] 5784: [info] AssemblyLoadFinished: Datadog.Trace.ClrProfiler.Managed v1.17.0 matched profiler version v1.17.0
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from <>c__DisplayClass0_0.<Main>b__0() to System.Data.Common.DbCommand.ExecuteNonQuery() 167772201 with calls to Datadog.Trace.ClrProfiler.Integrations.AdoNet.DbCommandIntegration.ExecuteNonQuery() 167772207
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpMessageInvoker.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpClientHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpClientHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpClientHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpClientHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.SocketsHttpHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from <SendAsync>d__4.MoveNext() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
[dotnet.exe] 5784: [info] *** JITCompilationStarted() replaced calls from <SendAsync>d__4.MoveNext() to System.Net.Http.HttpMessageHandler.SendAsync() 100663996 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773583
```

and the Trace UI shows an entry for `SqlConnectionTestCore` and `SqlConnectionTestCore-sql-server`.

If I run the same code in the aspnetcore 3.1.5 runtime container I get this:
```
[dotnet] 294: [info] Datadog CLR Profiler 1.17.0 64-bit
[dotnet] 294: [info] Environment variables:
[dotnet] 294: [info]   DD_TRACE_ENABLED=
[dotnet] 294: [info]   DD_TRACE_DEBUG=false
[dotnet] 294: [info]   DD_DOTNET_TRACER_HOME=
[dotnet] 294: [info]   DD_INTEGRATIONS=/opt/datadog/integrations.json
[dotnet] 294: [info]   DD_PROFILER_PROCESSES=
[dotnet] 294: [info]   DD_PROFILER_EXCLUDE_PROCESSES=
[dotnet] 294: [info]   DD_AGENT_HOST=192.168.210.143
[dotnet] 294: [info]   DD_TRACE_AGENT_PORT=
[dotnet] 294: [info]   DD_ENV=
[dotnet] 294: [info]   DD_SERVICE=
[dotnet] 294: [info]   DD_VERSION=
[dotnet] 294: [info]   DD_DISABLED_INTEGRATIONS=
[dotnet] 294: [info]   DD_CLR_DISABLE_OPTIMIZATIONS=false
[dotnet] 294: [info]   DD_TRACE_DOMAIN_NEUTRAL_INSTRUMENTATION=0
[dotnet] 294: [info]   DD_AZURE_APP_SERVICES=
[dotnet] 294: [info]   APP_POOL_ID=
[dotnet] 294: [info]   DOTNET_CLI_TELEMETRY_PROFILE=
[dotnet] 294: [info] Profiler attached.
[dotnet] 294: [info] JITCompilationStarted: Startup hook registered in function_id=140052885976464 token=100663297 name=SqlConnectionTestCore.Program.Main(), assembly_name=SqlConnectionTestCore app_domain_id=27330672 domain_neutral=0
[dotnet] 294: [info] ModuleLoadFinished: Datadog.Trace.ClrProfiler.Managed.Loader loaded into AppDomain 27330672 clrhost
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052886380784 token=100663308 caller_name=<>c__DisplayClass0_0.<Main>b__0() target_name=System.Data.Common.DbCommand.ExecuteNonQuery()
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052901236648 token=100664106 caller_name=System.Net.Http.HttpMessageInvoker.SendAsync() target_name=System.Net.Http.HttpMessageHandler.SendAsync()
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052901248472 token=100664006 caller_name=System.Net.Http.HttpClientHandler.SendAsync() target_name=System.Net.Http.HttpMessageHandler.SendAsync()
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052901248472 token=100664006 caller_name=System.Net.Http.HttpClientHandler.SendAsync() target_name=System.Net.Http.HttpMessageHandler.SendAsync()
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052901248472 token=100664006 caller_name=System.Net.Http.HttpClientHandler.SendAsync() target_name=System.Net.Http.HttpMessageHandler.SendAsync()
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052901256680 token=100665070 caller_name=System.Net.Http.SocketsHttpHandler.SendAsync() target_name=System.Net.Http.HttpMessageHandler.SendAsync()
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052929264064 token=100665080 caller_name=<SendAsync>d__4.MoveNext() target_name=System.Net.Http.HttpMessageHandler.SendAsync()
[dotnet] 294: [warn] JITCompilationStarted skipping method: Method replacement found but the managed profiler has not yet been loaded into AppDomain with id=27330672 function_id=140052929264064 token=100665080 caller_name=<SendAsync>d__4.MoveNext() target_name=System.Net.Http.HttpMessageHandler.SendAsync()
```

and only the manual trace appears in the UI.

So for some reason "the managed profiler has not yet been loaded into AppDomain".

**Comment by rlaveycal** [comment]
Downgrading the referenced DD.Trace and the installed profiler to 1.7.0 and running in a aspnet core 2.2.7 container works:
```
[dotnet] 180: [info] Datadog CLR Profiler 1.7.0
[dotnet] 180: [info] Environment variables:
[dotnet] 180: [info]   DD_TRACE_ENABLED=
[dotnet] 180: [info]   DD_TRACE_DEBUG=
[dotnet] 180: [info]   DD_INTEGRATIONS=/opt/datadog/integrations.json
[dotnet] 180: [info]   DD_PROFILER_PROCESSES=
[dotnet] 180: [info]   DD_PROFILER_EXCLUDE_PROCESSES=
[dotnet] 180: [info]   DD_AGENT_HOST=192.168.210.143
[dotnet] 180: [info]   DD_TRACE_AGENT_PORT=
[dotnet] 180: [info]   DD_ENV=
[dotnet] 180: [info]   DD_SERVICE_NAME=
[dotnet] 180: [info]   DD_DISABLED_INTEGRATIONS=
[dotnet] 180: [info]   DD_CLR_DISABLE_OPTIMIZATIONS=false
[dotnet] 180: [info] Profiler attached.
[dotnet] 180: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpMessageInvoker.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100664048 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773384
[dotnet] 180: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpClientHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100664048 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773384
[dotnet] 180: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpClientHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100664048 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773384
[dotnet] 180: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.HttpClientHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100664048 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773384
[dotnet] 180: [info] *** JITCompilationStarted() replaced calls from System.Net.Http.SocketsHttpHandler.SendAsync() to System.Net.Http.HttpMessageHandler.SendAsync() 100664048 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773384
[dotnet] 180: [info] *** JITCompilationStarted() replaced calls from <SendAsync>d__4.MoveNext() to System.Net.Http.HttpMessageHandler.SendAsync() 100664048 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773384
[dotnet] 180: [info] *** JITCompilationStarted() replaced calls from <SendAsync>d__4.MoveNext() to System.Net.Http.HttpMessageHandler.SendAsync() 100664048 with calls to Datadog.Trace.ClrProfiler.Integrations.HttpMessageHandlerIntegration.HttpMessageHandler_SendAsync() 167773384
```

Running on 1.17.0 in 2.2 doesn't

**Comment by lucaspimentel** [comment]
Thanks for reporting this. At first glance, it looks like you are having different issues.

@okezieokpara's logs contain these error message:
```
Unable to communicate with the trace agent at "http://172.31.27.28:8126/v0.4/traces"
```

And @rlaveycal's logs have this:
```
Method replacement found but the managed profiler has not yet been loaded into AppDomain
```

Can you both create support tickets by emailing support@datadoghq.com? Please include your logs  and reference this github issue. Thanks.

**Comment by okezieokpara** [comment]
thanks @lucaspimentel Indeed I had seen logs earlier and that was because the trace agent wasn't installed. Hence the message:
`Unable to communicate with the trace agent at "http://172.31.27.28:8126/v0.4/traces`
Now I can't see any logs at all and no traces received and no traces sent.
I had contacted support and they don't seem to have helped so far.

**Comment by gpltaylor** [comment]
I am also getting the same issues after trying for over a week to get a simple app to log tracing.

When targeting dotnet core 2.2 using DD 1.17.0 the app fails to log tracking to the /var/log/datadog/dotnet folder. The "dotnet-profile.log" file is also NOT created.

Reverting to  version 1.7.0.. the /var/log/datadog/dotnet-profiler.log is being populated but the dotnet folder is empty and nothing is showing on the dashboard! 

I will post here if I discover the solution.

**Comment by gpltaylor** [comment]
I've just created a brand new app and added to my existing docker-compose platform. The new app is using dotnet 3.1 and dd-trace-dotnet 1.17.0. This worked perfectly! Logs hitting the folder "/var/log/datadog/dotnet" and more importantly.. it's showing up in the dashboard.

Ok, the only thing I can think of is to upgrate my apps to 3.1

**Comment by gpltaylor** [comment]
I've upgraded one of my services from dotcore.2.2 to 3.1 (with as little code change as possible) and this was successful. I didn't make any changes to my Docker/compose process. As 2.2 is dead then this is not a huge issue but I would strongly recommend updating the documentation to state that dotnet 2.2 doen't work with autotomatic Instruction. Note that i've not testing if manual works...
