### ISSUE TITLE
Statsd client crashes the entire user application due to lack of thread safety

### ISSUE THREAD

**Issue by zaneclaes** [DataDog/dd-trace-dotnet#950]
**Describe the bug**
[This method](https://github.com/DataDog/dd-trace-dotnet/blob/5e1575aa94dc53f65e51227ad5e90fc44736f903/src/Datadog.Trace/Vendors/StatsdClient/Statsd.cs#L323-L329) is not thread-safe:

```
Unhandled exception. System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Datadog.Trace.Vendors.StatsdClient.Statsd.Send()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

Despite the use of a `ConcurrentBag`, no protections (lock/semaphores/etc.) are offered against mutation of the bag during the execution of the `Send` function. Since this happens outside the context of the user's application code, the uncaught exception causes the entire application to crash.

**To Reproduce**
Like many thread safety issues, this one is spurious. If the sequence is modified while the `Send()` method is executing, the value of the count will change and thereby cause the above exception.

**Expected behavior**
Datadog shouldn't crash the application.

**Runtime environment (please complete the following information):**
- Instrumentation mode: NuGet Package
- Tracer version: 1.19.3
- OS: linux (Docker)
- CLR: dotnetcore 3.1

**Comment by macrogreg** [comment]
Internal tracker:
https://datadoghq.atlassian.net/browse/DOTNET-284

**Comment by macrogreg** [comment]
@kevingosse  FYI
